name: 'helllicht/slack-action'
description: 'helllicht internal slack-action'

inputs:
    slackToken:
        description: 'Slack bot token'
        required: true
    channel:
        description: 'Slack Channel ID'
        required: true
    success:
        description: 'Success or not ("true" or "1" = success | all other values are failed)'
        required: true
    commitMessage:
        description: '(Optional) Pass the commit message "${{ github.event.head_commit.message }}"'
        required: false
        default: ''
    customMessage:
        description: '(Optional) Write your custom message (if used, no branch and commit information will be shown!)'
        required: false
        default: ''
    customIcon:
        description: '(Optional) Choose a custom icon'
        required: false
        default: ''

runs:
    using: 'node12'
    main: 'dist/index.js'
