name: 'helllicht/slack-action'
description: 'helllicht internal slack-action'

inputs:
    slackToken:
        description: 'Slack bot token'
        required: true
    channel:
        description: 'Slack Channel name'
        required: true
    success:
        description: 'Success or not ("true" or "1" = success | all other values are failed)'
        required: true
    commitMessage:
        description: '(Optional) Pass a commit message'
        required: false
        default: ${{ github.event.head_commit.message }}
    committer:
        description: '(Optional) Pass a committer (user)'
        required: false
        default: ${{ github.event.head_commit.committer.name }}
    customMessage:
        description: '(Optional) Write your custom message (if used, no branch and commit information will be shown!)'
        required: false

runs:
    using: 'node12'
    main: 'dist/index.js'
